# Generated by Django 5.2.4 on 2025-08-15 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='URL de la imagen')),
                ('event_country', models.CharField(max_length=100, verbose_name='País del evento')),
                ('event_state', models.CharField(max_length=100, verbose_name='Estado/Provincia')),
                ('event_city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('event_date', models.DateField(verbose_name='Fecha del evento')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('photographer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fotógrafo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Imagen destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['-event_date', '-created_at'],
                'unique_together': {('pic_url',)},
            },
        ),
    ]
