# Generated by Django 5.2.4 on 2025-08-15 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('artist', models.CharField(max_length=100, verbose_name='Artista')),
                ('album', models.CharField(max_length=200, verbose_name='Álbum')),
                ('lyrics', models.TextField(verbose_name='Letra')),
                ('genre', models.CharField(default='Unknown', max_length=50, verbose_name='Género')),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Año')),
                ('duration', models.CharField(default='Unknown', help_text='Formato: MM:SS', max_length=10, verbose_name='Duración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ['title'],
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
